{{- if .Values.nginx.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: nginx
data:
  config: |-
{{ .Values.nginx.config | indent 4 }}
{{- end }}
