apiVersion: v2
name: lsdcontainer-bastion
version: "1.0.18"
appVersion: "1.0.0"
kubeVersion: "v1.11.0"
description: A Helm chart for LSDContainer for a bastion server that will house all services LSD uses for OKD/RKE/K8S deployments
keywords:
  - lsdcontainer
  - kubernetes
  - bastion
home: https://github.com/lsdopen/charts
sources:
  - https://github.com/lsdopen
maintainers: 
  - name: LSD
    email: support@lsdopen.io
    url: https://lsdopen.io
deprecated: false
tillerVersion: "=>v3.2.1"
