apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ahoy-server
  name: ahoy-properties-prod
  namespace: ahoy
data:
  application-prod.properties: |
    ahoy.repo-path=./cache/repo
    ahoy.host={{ .Values.ahoy.host }}
    ahoy.cluster-type={{ .Values.ahoy.clusterType }}
    ahoy.auth.client-id={{ .Values.ahoy.auth.clientId }}
    ahoy.auth.issuer={{ .Values.ahoy.auth.issuer }}
    ahoy.auth.jwk-set-uri={{ .Values.ahoy.auth.jwkSetUri }}

    server.port=8080

    spring.datasource.url=jdbc:postgresql://ahoy-postgresql.ahoy.svc/ahoy
    spring.datasource.platform=postgres
    spring.datasource.username={{ .Values.postgresql.postgresqlUsername }}
    spring.datasource.password={{ .Values.postgresql.postgresqlPassword }}
    spring.datasource.driverClassName=org.postgresql.Driver
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
