apiVersion: v1
kind: Service
metadata:
  labels:
    app: ahoy-server
  name: ahoy-server
  annotations:
    cloud.google.com/app-protocols: '{"8080-tcp":"HTTP"}'
    service.alpha.kubernetes.io/app-protocols: '{"8080-tcp":"HTTP"}'
spec:
  selector:
    app: ahoy-server
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
  type: NodePort
